## changes names generated by novogene to be compatible with fastq2bam/ATACseq pipelines. run from raw_data directory.
mkdir -p fastq

mv */*.fq.gz fastq

for oldname in *L1_1*; do
	newname=`basename $oldname | sed 's/_L1_1.fq.gz/_S00_R1_001.fastq.gz/'`
	mv $oldname $newname
done

for oldname in *L1_2*; do
	newname=`basename $oldname | sed 's/_L1_2.fq.gz/_S00_R2_001.fastq.gz/'`
	mv $oldname $newname
done

